site_name: ML integration in CMSSW
site_url: https://github.com/castaned/ML-integration-CMSS/documentation
theme:
    name: material

    palette:
      # Dark mode
      - scheme: slate
        toggle:
          icon: material/weather-sunny
          name: Light mode
        primary: amber
        accent: indigo

      # Light mode
      - scheme: default
        toggle:
          icon: material/weather-night
          name: Night mode
        primary: amber
        accent: indigo

    font:
      text: Merriweather Sans
      code: JetBrains Mono

    features:
      - navigation.indexes

nav:
  - Getting started:
    - getting-started/01_overview.md
    - getting-started/02_architecture.md
  - CERN Computing Environment:
    - cern-systems/01_lxplus.md
    - cern-systems/02_storage.md
    - cern-systems/03_computing-resources.md
    - cern-systems/04_CMSSW.md
    - cern-systems/05_GRID-authentication.md
    - cern-systems/06-NanoAOD.md
    - cern-systems/07_dataset-discovery.md 
  - Framework:
    - framework/01_architecture.md
#    - framework/02_data-processing.md
#    - framework/03_ml.md
    - framework/04_framework-setup.md
  - Example of usage:
    - usage/01_usage.md

markdown_extensions:
   - admonition
   - pymdownx.details
   - pymdownx.superfences
   - footnotes
   - attr_list
   - md_in_html