---
convertion:
  input_dirs:
    - "/eos/user/v/vminjare/nanoFiltered/WprimeToWZToWlepZlep_narrow_M1000_TuneCP5_13TeV-madgraph-pythia8_RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1_NANOAODSIM"
    - "/eos/user/v/vminjare/nanoFiltered/ZGToLLG_01J_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8_RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1_NANOAODSIM"

  tree_name: "Events"

  branches: "all"
#    - "A_Dr_Z"
#    - "A_Lep1Z_eta"
#    - "A_Lep1Z_phi"
#    - "A_Lep1Z_pt"
     
  output_dir: "/eos/user/v/vminjare/nanoFiltered_h5"
