---
convertion:
  input_dirs:
    - ""
    - ""
    
  tree_name: ""
  
  branches:
      - ""
      - ""
  
# If you do not have jagged arrays leave it as null. If you use, the default value is 10
  max_jagged_len: null
  
  eos_output_dir: ""

condor_params:
  executable_file: "run_conversion.sh"
  cpus: 1
  gpus: 0
  mem: 1.5GB
  disk: 2GB
  job_flavour: "espresso" # 20 minutes

