---
data:
  input_paths:
    - ""
    - ""

  
  output_path: ""

  features:
    - ""
    - ""
    

  label: ""

  num_classes: 
  
model:
  name: ""

  type: "mlp"

  ideal_accuracy: 

  num_models: 