---
data:
  input_paths:
    - ""
    - ""

  
  output_path: ""

  features:
    - ""
    - ""

  label: ""

  num_classes: 
  
  # Leave this as null if you do not want to apply a mapping
  label_mapping: null
  
model:
  name: ""

  type: ""

  ideal_accuracy: 

  num_models:
  