---
data:
  path:
    - "/eos/user/v/vminjare/nanoFiltered_h5/WprimeToWZToWlepZlep_narrow_M1000_TuneCP5_13TeV-madgraph-pythia8_RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1_NANOAODSIM"
    -  "/eos/user/v/vminjare/nanoFiltered_h5/ZGToLLG_01J_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8_RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1_NANOAODSIM"

  
  output_path: ".output"

  features:
    - "A_Dr_Z"
    - "A_Zmass"
    - "MET_pt"
    - "B_Zmass"
    - "B_Dr_Z"
    

  labels: "Dataset_ID"

model:
  ai_model: "mlp"

  ai_model_class: "multiclass"

  ideal_accuracy: 95

  num_models: 3