---
proxy:
  generate: 1 # 1 yes, 0 no
  voms: "cms"
  proxy_time: "192:00"
  proxy_path: "$HOME/.globus/x509up_u$(id -u)"

data_processing:
  condor_params:
    executable_file: "run_filter.sh"
    cpus: 1
    gpus: 0
    mem: 1.5GB
    disk: 2GB
    job_flavour: "espresso" # 20 minutes
  processing_script: ""
  eos_output_dir: ""
  afs_cms_base: ""
  redirector: "cms-xrd-global.cern.ch"
  datasets:
    - LFN: ""
      ID:  
      amount: # -1 is all root files
    - LFN: ""
      ID: 
      amount: 
    
