---
proxy:
  generate: 0 # 1 yes, 0 no
  voms: "cms"
  proxy_time: "192:00"
  proxy_path: "$HOME/.globus/x509up_$(id -u)"

data_processing:
  condor_params:
    executable_file: "run_filter.sh"
    cpus: 1
    gpus: 0
    mem: 1.5GB
    disk: 2GB
    job_flavour: "espresso" # 20 minutes
  processing_script: "src/repo/script"
  eos_output_dir: "/eos/user/directory/data/root"
  afs_cms_base: "/afs/cern.ch/user/directory/env/CMSSW"
  redirector: ""
  datasets:
    - FLN: ""
      ID: 0 # For ML training, it is better to start at 0
      amount: 3 # -1 is all root files
    - FLN: ""
      ID: 1
      amount: -1
    
